### ISSUE TITLE
Weird bug after restarting app

### ISSUE THREAD

**Issue by Shiny-hunter2022** [zyro670/PokeViewer.NET#10]
When i use the app on cold start, you see the gameboy icon when you put the IP and it seems to work fine, but lets say after i put the computer to sleep and i try to use the app again later the gameboy icon doesn't load anymore and while trying to fetch eggs it takes like 1 minute to update 1 egg and then it goes back into sandwich mode and keeps doing the same 1 minute wait until refresh then back to sandwich, i noticed that restarting the computer fixes this bug.

**Comment by zyro670** [comment]
See if you can still replicate this on latest release. If you still can, try to disconnect the app before putting your PC to sleep.
