### ISSUE TITLE
Minor Oversight with Breeding

### ISSUE THREAD

**Issue by CakeFlour** [zyro670/PokeViewer.NET#11]
Since making sandwiches gives Pokemon EXP, if a Pokemon learns a move after leveling up from a pick-nick it can cause an interference. 
Solutions include
- Having "Skip learning moves" turned on in game options
- Have all pokemon level 100 (or have no more moves to learn)

Might be worth making a note on the Wiki for this and NotForkBot

**Comment by zyro670** [comment]
thank you! wiki has been updated.
