### ISSUE TITLE
Mass Outbreak False Positive

### ISSUE THREAD

**Issue by lfmundim** [zyro670/PokeViewer.NET#13]
I was "crawling" for a Vivillon/Scatterbug mass outbreak. I let the bot do its thing and after a while it found me a vivillon outbreak as the 8th one

![image](https://user-images.githubusercontent.com/15164001/225374085-97f66c3f-c393-4d01-a0f5-0b41d5f43b5b.png)

I could see outbreaks 1-6 on the map so I figured that maybe i had to clear out 2 outbreaks for it to show up. I started clearing the flittle one and went to refresh the scan, and now 7 and 8 are gone. 

![image](https://user-images.githubusercontent.com/15164001/225374844-2f18472c-8f40-425c-8f5f-ced20332a53e.png)

I did transfer a postcard from Go before i started killing flittle.

**Comment by lfmundim** [comment]
For completeness, i cleared the flittle outbreak and it didn't budge
![image](https://user-images.githubusercontent.com/15164001/225378036-21159913-e92d-4f0f-ad9b-9cf2161ff0a8.png)

**Comment by zyro670** [comment]
Did you happen to see if the total outbreak count showed as 8 when rufflet and viv were present?

**Comment by lfmundim** [comment]
hmmm i didn't see... ill do some more scanning to see if i can reproduce it with other species

**Comment by zyro670** [comment]
In the save block it always rolls 8 outbreaks from what I've seen, but the total possible on map does not always match this. I read another part of the save block that shows total outbreak count on map, which is why we quit early from reading. if you are able to reproduce then maybe it's the wrong one to be reading but it's been correct for most tests. 

Were you in general overworld? I've seen some weird situations where if I'm in area zero not all outbreaks show up on the map.

**Comment by lfmundim** [comment]
Ill take a peek if i mistakenly changed that code part, but i dont think so.

managed to reproduce it again
![image](https://user-images.githubusercontent.com/15164001/225384232-a07e0ea9-ff73-447e-8400-db243c45d2b2.png)

I can see outbreaks 1-4, can't see 5-8, and it registers 8

And yes, I was on the overworld both times (1st time on a Pokecenter, Alfornada. 2nd time North Area 3 flight point)

**Comment by lfmundim** [comment]
and yeah it seems to be using the address block you mentioned for valid outbreaks to quit early

![image](https://user-images.githubusercontent.com/15164001/225385143-7aa99d84-154b-43be-aa7d-d48a55b16574.png)

**Comment by zyro670** [comment]
Hmm, seems like it occurs whenever vivillon is present. I'll have to see search for one later and do a dump to see if there's any significant changes to the save block. Thanks for finding that out.

**Comment by zyro670** [comment]
Actually maybe that is my error? Can you try moving the outbreak total check to after we save the game? I'm at work so I can't test right now

**Comment by lfmundim** [comment]
It might be a coincidence. I set vivillon as a stopper. Ill try to reproduce it without vivillon after im done with this outbreak :P



> Actually maybe that is my error? Can you try moving the outbreak total check to after we save the game?

sure thing. Will post back with results in a few.

**Comment by zyro670** [comment]
If you can still reproduce after moving it to after we save but before reading the blocks, then viv probably does something to it. But it might be my error here 😂

**Comment by lfmundim** [comment]
> If you can still reproduce after moving it to after we save but before reading the blocks, then viv probably does something to it. But it might be my error here 😂

yup! seems to be human error after all :) the fix is issued #14

**Comment by zyro670** [comment]
Thank you!! 🙏🏼 💯 very much appreciated.
