### ISSUE TITLE
Have to restart game after shiny egg

### ISSUE THREAD

**Issue by maplessativa** [zyro670/PokeViewer.NET#15]
Any time I get an egg what I filtered for on the egg feature, I have to restart the game. If I try to start searching for more eggs after what I filter for(any shiny), then my first egg will be flagged and the information from the last egg I filtered for. If I restart the bot it does it again. Same IVs size all of that and of course, shiny. Looks like restarting the game solves the issue. 

P.S. sorry if I wrote this a wrong way I'm new to commenting but I love your releases so I figured I'd try to help out. ^-^'

**Comment by zyro670** [comment]
Hello! Should be fixed in the next release :)
