### ISSUE TITLE
Suggestion: Add notes to Wiki on the recent change to the .sve command and Discord Integration.

### ISSUE THREAD

**Issue by CakeFlour** [zyro670/PokeViewer.NET#18]
I recently got the latest version of NotForkBot and was confused why the embed command "sve" wasnt working anymore, but after a little research I eventually found the change. 
The new bot integration I see now just has it on automatically for channels that are whitelisted for echo notifications.
And additionally the embed notifications (afaik) only trigger for Shiny Eggs, and not normal ones. (which also caused a little confusion when trying to test it)
I think adding a small note into the Wiki for Pokeviewer and NotForkBot would probably help clear up some confusion others might have about this.

Please and Thank-you. (And thank you for making these amazing programs!)

**Comment by zyro670** [comment]
The respective wikis has it on there to use $embedhere for egg/overworld and $echohere for raids.

If your stop condition is non shiny you'll get pinged for non shiny with Sysbot.
