### ISSUE TITLE
Writing Memory

### ISSUE THREAD

**Issue by lfmundim** [zyro670/PokeViewer.NET#2]
Why would you need to write into memory when you read for eggs? Seems unnecessary

https://github.com/zyro670/PokeViewer.NET/blob/baae264b3d75a8923f4e6ce0b77e8b8038a79073/PokeViewer.NET/SubForms/Egg%20Viewer.cs#L45

**Comment by zyro670** [comment]
Iirc the game still stores the last egg data there even when the picnic closes. Can’t remember if it considers that egg 1 or not after the first sandwich is made but it might be leftover code I didn’t remove from a prior test. Can test it after work and remove if it doesn’t consider it egg 1.

**Comment by lfmundim** [comment]
Thanks for the swift reply!

Alongside that there is also another write too

https://github.com/zyro670/PokeViewer.NET/blob/baae264b3d75a8923f4e6ce0b77e8b8038a79073/PokeViewer.NET/SubForms/Egg%20Viewer.cs#L46

Whats its purpose?

**Comment by lfmundim** [comment]
> Iirc the game still stores the last egg data there even when the picnic closes. Can’t remember if it considers that egg 1 or not after the first sandwich is made but it might be leftover code I didn’t remove from a prior test. Can test it after work and remove if it doesn’t consider it egg 1.

might be a better idea to compare the "first" egg you get from a picnic to the last you got from the previous. How stable/safe is writing memory?

**Comment by zyro670** [comment]
The offset being used had different values for Scarlet and Violet but both would increment by 1-2 when doing the specific part of the routine. Scarlet was 1,2,3 then violet was 2,3,4 iirc but sometimes a 5 would show up. Was gonna use a tertiary to handle it until I saw the 5 randomly. So I just have it start both at 1 for each game. 

To the writing memory part, there hasn’t been any issues im aware of for any task sysbot.base related for these things where we just write locally. 

If it does consider it egg 1, I’ll have it take do an egg read on start instead and compare that for after the sandwich is made.

**Comment by lfmundim** [comment]
I see. I'm asking because I'm tinkering around the EggView and for some reason every time it stops either naturally (found something) or HardStop, if i walk around for 5seconds ingame, the game crashes, so im trying to find out why

**Comment by zyro670** [comment]
Hmm, it could be the egg data clear. If you want to try removing it locally and PRing if that fixes it for you I could merge. I won’t be home for another 9 hours before I can make the change.

**Comment by lfmundim** [comment]
I commented out both writes and am running some loops to see if everything still works fine. I saw that the picnic menu is used only on making a sandwich and I started it out without eating, so I'm waiting for it to naturally go eat a sandwich when needed.

if it works without both writes Ill open a PR as such. If it doesnt work ill try without the egg overwrite. why do you think the picnic menu write is safe while the egg one isnt? is it because picnic you're writing a theoretical valid value and egg you're just removing everything?

**Comment by zyro670** [comment]
It might be that some other game function is trying to read the eggdata but there’s nothing there. Kinda weird it causes you to crash when at that point there’s already new eggs that have overwritten any blank data. 

If you did comment out the picnic write and are on Scarlet it should work as intended, if you’re on Violet it might fail with the default values.

**Comment by lfmundim** [comment]
> It might be that some other game function is trying to read the eggdata but there’s nothing there. Kinda weird it causes you to crash when at that point there’s already new eggs that have overwritten any blank data.

There are no new eggs. It crashes following this scenario:
* It finds something/hard stop
* I get stuff from basket or just close picnic
* i walk around
* crashes

weird is that it only crashes when walking around. if i go about boxes, save etc it works fine. i just cant walk.

> If you did comment out the picnic write and are on Scarlet it should work as intended, if you’re on Violet it might fail with the default values.

should it write 2 instead of 1 on Violet? I'm on scarlet but we want a solution for both versions right? Both lines commented out its as you said, its working as intended on Scarlet

**Comment by zyro670** [comment]
Okay so the blank write seems to be causing it, I’ve run it the last few days but haven’t had it crash one me. But I think I wasn’t walking actually just staying in place and resetting the game. 

From my testing violet’s default value was 2, but if I wrote it to 1, it’ll stay with 1 as the default. It’s not an actual “picnic” offset but just an arbitrary one that incremented in a way that could be used for the routine. I could probably try doing a tertiary again depending on game version, I don’t remember how/when the random 5 showed up. The values in the comments here are for scarlet, for violet is was +1 to all of these.
https://github.com/zyro670/PokeViewer.NET/blob/baae264b3d75a8923f4e6ce0b77e8b8038a79073/PokeViewer.NET/SubForms/Egg%20Viewer.cs#L341

**Comment by lfmundim** [comment]
> Okay so the blank write seems to be causing it, I’ve run it the last few days but haven’t had it crash one me. But I think I wasn’t walking actually just staying in place and resetting the game.

by blank write you mean the 0x01 write onto picnic menu memory, not the egg? 👀

what if instead of reading memory values to see if it is `InPicnic` it uses time delays to ensure animations etc are done?

**Comment by zyro670** [comment]
The blank write to egg data, not the picnic write. I’m at work so I’m not doing any actual testing right now 😂 

I didn’t do time delays since it would probably be different for every switch/sandwich if someone used different ingredients. Not sure if number of mons in picnic would make any difference to cutscene length. If you were able to produce a routine with accurate delays we could probably make another check box to use time delays vs memory reads for that part.

**Comment by lfmundim** [comment]
Commenting out both memory writes ended up on eventually the bot stopping with main menu open, I'll try keeping the picnic write and change the egg write into direct comparison then since you believe the issue lies on egg. Will test and let you know shortly

**Comment by zyro670** [comment]
I also have this routine on my sysbot fork but it doesn’t have the blank write to egg data. So I really must have left that there from an initial testing, woops 😂

sounds good let me know how it goes! Thank you for bringing it to my attention.

**Comment by lfmundim** [comment]
Thank you for writing this! I needed it a lot to the point I started doing my releases as you didn't :p will let you know asap!

**Comment by zyro670** [comment]
Oh I didn’t do releases since I have the auto builds via azure haha.

**Comment by zyro670** [comment]
Pushed updates yesterday to the overall routine for better stability.

**Comment by zyro670** [comment]
Will go ahead and close as the line was removed
