### ISSUE TITLE
Wide Scan without attempting to save

### ISSUE THREAD

**Issue by Unknown-Warrior** [zyro670/PokeViewer.NET#20]
I would like an option to disable the forced save function when trying to wide scan in SV.

**Comment by zyro670** [comment]
It has to save in order to update the block with what's currently in the overworld. Without saving it'll keep scanning the previous state from when it last saved.

**Comment by Unknown-Warrior** [comment]
Ah, I was not aware that's how that worked.
Can you add what the bot does when attempting to scan to the wiki for people in the future like me who were confused why it's trying to take control and save?

**Comment by zyro670** [comment]
Yup I can do that! There is a way to let it scan everything as it's "spawns" but the setup is not very simple and I haven't been able to incorporate it to work with botting properly. The other issue is the game also "generates" an encounter for everything even when it shouldn't. If you open your map, all those sprites have generated data, it's very weird.
