### ISSUE TITLE
Outbreaks show incomplete info

### ISSUE THREAD

**Issue by Branfurrd** [zyro670/PokeViewer.NET#25]
Last 2 versions have same issue: missing species and their quantity on right column of outbreak window. 3.0.3 meanwhile displays everything right. I have latest usb-botbaseZ which 3.1.1 suggests to install if this info have relevance.
How it looks in 3.1.0-3.1.1:
![3 1 1](https://github.com/user-attachments/assets/82ac74cd-e8f6-4c29-ae1e-4245045f3f3a)
How it supposed to be (3.0.3 e.g.)
![3 0 3](https://github.com/user-attachments/assets/345e5c48-ab11-4bd1-abfa-975396a085df)

**Comment by zyro670** [comment]
Should be fixed on latest. Let me know if it still persists.
