### ISSUE TITLE
EggBot not activating in game?

### ISSUE THREAD

**Issue by CakeFlour** [zyro670/PokeViewer.NET#6]
I'm attempting to set up eggbot and am 99% sure I've been doing everything correctly.
When I go to click "Fetch" however, nothing occurs in-game, but the Program itself is confirmed to be connected since it still gives back information on generated eggs. After clicking fetch, nothing occurs, then the window says it's made 1 sandwich

I've attempted to troubleshoot numerous problems and nothing seems to fix it.
- Sysbot is up to date, and my switch has been rebooted.
- PC has been Rebooted after installing .NET 07
- Controllers are disconnected from Console
- Connected to the Internet In-game
- Standing in the spot dictated in the wiki (right after opening up the pick-nick)
- Boxes checked are "Stop on Shiny" "Eat on Start" and "Eat Again" Everything else left unchecked or set to default value.
- Can confirm the bot is connected since I still get back data on eggs that appear normally.

If there's anything else I've missed please let me know.

**Comment by zyro670** [comment]
Hello~

Can you try a previous build from before the net7 update and see if that resolved your issue? If it does then something is happening on my end from when I bumped it to net7. If it still doesn’t work then try reinstalling the latest sysbot.base from the link in the ReadMe. 

I’ll be home in 4 hours to take a look if it’s a net7 issue.

**Comment by CakeFlour** [comment]
I downloaded and ran version #20230131.1 with the same settings, but still no response in-game.
I made sure to update to the latest SysBot.base provided in the Readme before making the issue, but if I need to do it again for some reason I can.

**Comment by zyro670** [comment]
If the issue still occurs you can try using my sysbot.net fork, it has the egg routine as well for SV.

**Comment by CakeFlour** [comment]
After extensive troubleshooting (Thanks to Showdown Labs Discord) the issue was found.
The Sysbot was crashing due to the fact that my In-game Text speed was set to "normal" and not "fast"

So the issue was fixed immediately once that was changed and now the latest build of Pokeviewer works as intended.
It's a little silly all things considered, but I'm glad it was solved.

With this knowledge however, I think making a note somewhere on the Readme/Wiki that Text speed needs to be set to Fast int the event anyone else runs into this problem

**Comment by zyro670** [comment]
Glad it was a fix as simple as that! Thank you to all who helped troubleshoot, I’ve made note in the wiki to ensure text speed is set to fast. Will go ahead and close
