### ISSUE TITLE
Weird issue latest version

### ISSUE THREAD

**Issue by Shiny-hunter2022** [zyro670/PokeViewer.NET#9]
I updated to 1.0.2 and when i started the program the eggs in the basket count would just go up, from 1 - 10 in under 10 seconds, i restarted the program and console but it would still happen so for now i went back to the previous build

**Comment by zyro670** [comment]
Haven't been able to replicate this yet, but I'll keep an eye out for it. Will be releasing 1.1.0 this week once I finish a few more changes to the UI.

**Comment by zyro670** [comment]
lmk if you're still having issues on 1.1.0!

**Comment by Shiny-hunter2022** [comment]
Been using 1.1.0 now and no issues so far!! Maybe one bug That i found?? Unless intended but while using the program if you change tabs the connection gets terminated and it stops fetching eggs so you have to redo everything other than that all good! Thanks for the updates!

**Comment by zyro670** [comment]
Not intended but.. I am still looking into how to not let that happen 😂 ideally while fetching or reading boxes I'd like to lock the gui to that tab page. Will be included in 1.1.1 whenever I figure out how to do that. Hardstop seems to be having issues as well.

**Comment by zyro670** [comment]
On 1.1.1 you can now switch tab without the connection getting lost. Hard stop will go ahead and just reset the application for now as well. Going to close for now, thank you for the reports!
